import { ThemeProvider } from "@/providers/themeContext";
import Header from "@/components/UI/Header/Header";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

import { Nunito_Sans } from "next/font/google";

//👇 Configure our font object
const nunitoSans = Nunito_Sans({
  weight: ["300", "600", "800"],
  subsets: ["latin", "latin-ext"],
  display: "swap",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={nunitoSans.className}>
      <body>
        <ThemeProvider>
          <Header />
          <main>{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
